#!/usr/bin/env sh
#usage: ./timetable [-t] [-f <DD.MM.YYYY>] [-0] [-d <destination_directory>] [-s <source_directory>] \"from1 to1 ... fromN toN\""

#setting default parametres
a="/home/igorjan/206round/timetable"
b="/home/igorjan/documents/timetable"
flag=0;
today="";

function usage {
   echo "usage: ./timetable.sh [-t] [-f <DD.MM.YYYY>] [-0] [-d <destination_directory>] [-s <source_directory>] \"from1 to1 ... fromN toN\"" 
   exit
}

#parsing arguments
while getopts "0ts:d:f:" opt; do
  case $opt in
    \?) usage;;
    s) a=$OPTARG;;
    d) b=$OPTARG;;
    0) flag=1;;
    t) today="&date=today";;
    f) today="&date=$OPTARG";;
  esac
done

shift $(($OPTIND - 1))
if [ $# -eq 0 ]
	then usage
fi

arg=$1

#create source_directory, clean temporary files
mkdir -p $b

#setting script pathes
a="$a/loadtimetable.py"

#downloading timetable
python3 $a $b "$today" $flag $arg
