#!/usr/bin/env bash

#setting default parametres
a="/home/igorjan/206round/timetable"
b="/home/igorjan/new"
flag=1;
today=""
todayDate=$(date +"%d.%m.%Y")
tomorrow=$(date --date="tomorrow" +"%d.%m.%Y")
minutes=39

function usage {
   echo "usage: timetable [-t<oday>] [-<to>M<orrow>] [-f <dd.MM.yyyy>] [-0] [-o <destination_directory>] [-s <source_directory>] \"from1 to1 ... fromN toN\"" 
   exit
}

#parsing arguments
while getopts "0mto:s:d:f:n:" opt; do
  case $opt in
    \?) usage;;
    s) a=$OPTARG;;
    o) b=$OPTARG;;
    d) b=$OPTARG;;
    0) flag=0;;
    t) today="&date=$todayDate";;
    m) today="&date=$tomorrow";;
    f) today="&date=$OPTARG";;
    n) minutes=$OPTARG;;
  esac
done

shift $(($OPTIND - 1))
arg=$1
if [ $# -eq 0 ]
    then arg="Л С С Л"
fi

#create output directory
mkdir -p $b

#setting script pathes
a="$a/loadtimetable.py"

#downloading timetable
python3 $a $b "$today" $flag $minutes $arg
