#!/usr/bin/env bash
# [{
#   type: front,
#   name: damosFront,
#   container: nginx,
#   rep: http://bitbucket.org/konekon/1705-front-end.git,
#   server: http://konekon.ru/damos/                            #Backand URL
#   host: 1705.konekon.ru,                                      #Virtual host from internet
# }, {
#   type: node,
#   name: damosNode,
#   container: node,                                            #Default: type
#   rep: http://bitbucket.org/konekon/1705-back-end.git,
#   server: http://konekon.ru/,                                 #Server, backend is on
#   host: damos,                                                #Backend will be available on $server:81/$host
#   port: 20000,                                                #Port. It should be autogenerated(cauze doesn't have any meaning. But later)
#   arguments: "DATABASE='mysql://.....'"                       #Arguments to nodeJS on startup: $arguments node --harmony bin/www. Env with mode and host/port is already defined
# }]

#Staff  #{{{
settings="settings.json"
if [ ! -f $settings ]; then
    echo '[]' > "$settings"
fi

projects=`jq '.' $settings`

fail () {
    echo "$1"
    exit 1
}

usage () {
   echo "H" 
   exit 0
}

toNamedParams () {
    type=$1
    name=$2
    container=$3
    rep=$4
    server=$5
    host=$6
    port=$7
    arguments=$8
    if [ ! "$container" ]; then container="$type"; fi
}

addProject () {
    toNamedParams "$@"
    projects=`echo $projects | jq ". + [{
    \"type\": \"$type\",
    \"name\": \"$name\",
    \"container\": \"$container\",
    \"rep\": \"$rep\",
    \"server\": \"$server\",
    \"host\": \"$host\",
    \"port\": \"$port\",
    \"arguments\": \"$arguments\"
}]"`
}

getProjectByName () {
    found=`echo $projects | jq "map(select(.name == \"$1\"))[]"`
    foundName=`echo $found | jq -r '.name'`
    foundType=`echo $found | jq -r '.type'`
    foundContainer=`echo $found | jq -r '.container'`
    foundRep=`echo $found | jq -r '.rep'`
    foundServer=`echo $found | jq -r '.server'`
    foundHost=`echo $found | jq -r '.host'`
    foundPort=`echo $found | jq -r '.port'`
    foundArguments=`echo $found | jq -r '.arguments'`
    unset found
    if [ "$foundType" != "" ]; then found=true; fi
}

deleteProjectByName () {
    projects=`echo $projects | jq "map(select(.name != \"$1\"))"`
}

checkType () {
    if [ "$1" == "node" ] || [ "$1" == "front" ] || [ "$1" == "tarantool" ] || [ "$1" == "python" ]; then return; fi
    fail "Incorrect type!"
}





#}}}

#Options #{{{
OPTS=`getopt -o ht:n:c:r:s:h:p:a: -l type:,name:,container:,rep:,repository:,server:,host:,port:,arguments:,help -- "$@"`
if [ $? != 0 ]; then exit 1; fi
eval set -- "$OPTS"

#parsing arguments
while true ; do
    case "$1" in
        --help                    ) usage        ;shift;;

        -t | --type               ) type=$2      ;shift 2;;
        -n | --name               ) name=$2      ;shift 2;;
        -c | --container          ) container=$2 ;shift 2;;
        -r | --rep | --repository ) rep=$2       ;shift 2;;
        -s | --server             ) server=$2    ;shift 2;;
        -h | --host               ) host=$2      ;shift 2;;
        -p | --port               ) port=$2      ;shift 2;;
        -a | --arguments          ) arguments=$2 ;shift 2;;

        --                        ) shift; break;;
    esac
done #}}}

#Parsing # {{{
if [ "$1" == "create" ]; then # {{{
    if [ ! "$name" ] || [ ! "$type" ] || [ ! "$rep" ]; then fail "Type and name and rep are required!"; fi
    case "$name" in
        *\ *) fail 'Name cannot contain spaces!';;
    esac

    getProjectByName "$name"
    if [ "$found" ]; then fail "Project already exists!"; fi
    checkType $type

    addProject "$type" "$name" "$container" "$rep" "$server" "$host" "$port" "$arguments"
    if [ "$type" == "front" ]; then #{{{
        docker exec -ti "$container" bash -c "mkdir -p /home/nesuko && cd /home/nesuko && rm -rf $name && git clone $rep $name && cd $name && npm i && bower i -F --allow-root"
        docker exec -ti "$container" bash -c "rm -rf /var/www/$name && mkdir -p /var/www/$name"
        docker exec -ti "$container" bash -c "cd /home/nesuko/$name && SRV=$server npm run build && cp -r /home/nesuko/$name/dist /var/www/$name"
        docker exec -ti "$container" bash -c "echo -e \"server {
    listen   80;

    server_name $host;
    root /var/www/$name/dist;
    index index.html index.htm;

    location / {
        allow all;
        try_files \"'$'\"uri \"'$'\"uri/ /index.html =404;
    }
}\" > /etc/nginx/sites-available/$host"
        docker exec -ti "$container" bash -c "ln -fs /etc/nginx/sites-available/$host /etc/nginx/sites-enabled/$host"
        docker kill -s HUP $container
#}}}
    elif [ "$type" == "mysql" ]; then #{{{
        docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=y3l0l3k0r -e MYSQL_USER=external -e MYSQL_PASSWORD=y3l0l3k0r -e MYSQL_DATABASE=damos --restart=always -d mysql/mysql-server  --character-set-server=utf8 --collation-server=utf8_general_ci
#CREATE USER foo@'%' IDENTIFIED BY 'password';
#GRANT ALL PRIVILEGES ON *.* TO 'foo'@'%' WITH GRANT OPTION;
#FLUSH PRIVILEGES;
#}}}
    elif [ "$type" == "node" ]; then #{{{
        docker exec -ti "$container" bash -c "mkdir -p /var/node && cd /var/node && rm -rf $name && git clone $rep $name && cd $name && npm i && NODE_ENV=production HOST='$server:81/$host' PORT=$port $arguments pm2 start --name=$name --node-args='--harmony' bin/www && pm2 startup"

        docker exec -ti "$container" bash -c "echo -e \"location /$host/ {
        proxy_set_header Host \"'$'\"host;
        proxy_set_header X-Real-IP \"'$'\"remote_addr;
        proxy_set_header X-Forwarded-For \"'$'\"proxy_add_x_forwarded_for;
        proxy_pass http://localhost:$port/;
}\" > /etc/nginx/sites-available/locations/$name"
        docker exec -ti $container bash -c "nginx -s reload"
    fi #}}}
# }}}

elif [ "$1" == "pull" ]; then # {{{
    if [ ! "$name" ]; then fail "Name is required!"; fi
    getProjectByName "$name"
    if [ ! "$found" ]; then fail "Project with name '$name' is not found!"; fi

    if [ $foundType == "front" ]; then
        docker exec -ti $foundContainer bash -c "cd /home/nesuko/$foundName && git pull | grep 'bower\.json' && rm -rf bower_components && bower i -F --allow-root; SRV=$foundServer npm run build && cp -r /home/nesuko/$foundName/dist /var/www/$foundName"
    elif [ "$foundType" == "python" ]; then
        cd /home/igorjan/$foundName && git pull | grep 'requirements\.txt' && docker exec -ti "$foundContainer" bash -c "pip install -r requirements.txt"
        docker restart "$foundContainer"
    elif [ "$foundType" == "node" ]; then
        docker exec -ti "$foundContainer" bash -c "cd /var/node/$foundName && git pull | grep 'package\.json' && rm -rf node_modules && npm i"
        docker exec -ti "$foundContainer" bash -c "pm2 restart $foundName"
    fi
fi #}}}
# }}}

echo "$projects"
echo "$projects" > $settings


