#!/usr/bin/perl
$c = 0;
$b = 0;
while(<>)
{
    s/<.*?>//g;
    if (/^ *$/)
    {
        $c = $c + 1;
    }
    else
    {
        if ($c > 0)
        {
            $c = 0;
            if ($b == 1)
            {
                print "\n";
            }
        }
        $b = 1;
        s/^( )*(.*?)( )*$/$2/g;
        s/( )\1*/ /g;
        print;
    }
}
