#!/usr/bin/perl
use List::MoreUtils qw/ uniq /;
while(<>)
{
    while (/<a(\b|\b[^>]*?\b)href=\"(.*?)\".*?>/) 
    {
#        print "was: ", $_, "!\n";
        s/.*?<a(\b|\b[^>]*?\b)href=\"(.*?)\".*?>//;
#        print "\$_ = ", $_, "!\n";
#        print "\$1 = ", $1, "!\n";
#        print "\$2 = ", $2, "!\nnext\n";
        $s = $_;
        $_ = $2;
        s/^.*?:\/\/(.*)/$1/;
        s/^(.*?)(:|\/).*/$1/;
        s/^\..*//;
        push(@array, $_);
        $_ = $s;
    }
}
@array = sort(@array);
@array = uniq(@array);
$i = 0;
$size = @array;
while ($i < $size)
{
    if ($array[$i] ne "")
    {
        print $array[$i], "\n";
    }
    $i++;
}
